// <auto-generated />
using CustomDSATrainer.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomDSATrainer.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20250807110457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CustomDSATrainer.Domain.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Problem");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AverageExecutionTime")
                        .HasColumnType("REAL");

                    b.Property<string>("PathToExecutable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExecutionTime")
                        .HasColumnType("TEXT");

                    b.Property<uint>("MemoryLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathToExpectedOutputFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToInputFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToOutputFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimeLimit")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeOfStarting")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestCase");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DaysLogged")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LoggingStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerviousDayLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("TotalAttemptedTasks")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TotalSolvedProblems")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TotalUnsolvedProblems")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
