// <auto-generated />
using CustomDSATrainer.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomDSATrainer.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20250807112558_AddIndexes")]
    partial class AddIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CustomDSATrainer.Domain.AIReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathToCPPFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProblemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProblemStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("AIReview");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_Problem_Status");

                    b.ToTable("Problem");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AverageExecutionTime")
                        .HasColumnType("REAL");

                    b.Property<string>("PathToExecutable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProblemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExecutionTime")
                        .HasColumnType("TEXT");

                    b.Property<uint>("MemoryLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathToExpectedOutputFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToInputFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToOutputFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProblemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TimeLimit")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeOfStarting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Verdict")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("TestCase");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DaysLogged")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LoggingStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerviousDayLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("TotalAttemptedTasks")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TotalSolvedProblems")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TotalUnsolvedProblems")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.AIReview", b =>
                {
                    b.HasOne("CustomDSATrainer.Domain.Problem", "Problem")
                        .WithMany("AIReviews")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.Submission", b =>
                {
                    b.HasOne("CustomDSATrainer.Domain.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.TestCase", b =>
                {
                    b.HasOne("CustomDSATrainer.Domain.Problem", "Problem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("CustomDSATrainer.Domain.Problem", b =>
                {
                    b.Navigation("AIReviews");

                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
