using CustomDSATrainer.Domain;
using CustomDSATrainer.Domain.Enums;
using CustomDSATrainer.Domain.Interfaces.Repositories;
using CustomDSATrainer.Domain.Interfaces.Services;
using CustomDSATrainer.Domain.Interfaces.UnitOfWork;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CustomDSATrainer.Application.Services
{
    /// <summary>
    /// Provides the functionality for everything that has to do with a <see cref="TestCase"/>:
    /// <list type="bullet">
    /// <item>Initializing a test case</item>
    /// <item>Running a test case</item>
    /// <item>Saving a test case to the database</item>
    /// </list>
    /// </summary>
    public class TestCaseService : ITestCaseService
    {
        private IUserOutputService _userOutputService;
        private readonly IUserSourceLinkerService _userSourceLinkerService;
        private readonly IUnitOfWork _unitOfWork;
        public TestCaseService(IUserOutputService userOutputService, IUserSourceLinkerService userSourceLinkerService, IUnitOfWork unitOfWork)
        {
            _userOutputService = userOutputService              ?? throw new ArgumentNullException(nameof(userOutputService), "UserOutputService cannot be null.");
            _userSourceLinkerService = userSourceLinkerService  ?? throw new ArgumentNullException(nameof(userSourceLinkerService), "UserSourceLinkerService cannot be null.");
            _unitOfWork = unitOfWork                           ?? throw new ArgumentNullException(nameof(unitOfWork), "UnitOfWork cannot be null.");
        }

        /// <summary>
        /// Initializes the test case by running the user-generated executable.
        /// It calls <see cref="UserSourceLinkerService.RunCppExecutable(TestCase)"/> which captures the output generated by the user's executable and checks for time/memory limits.
        /// This function doesn't compare the expected output with the ones generated by the executable.
        /// </summary>
        /// <param name="testCase">The test case to be initialized.</param>
        /// <returns>A <see cref="TestCaseVerdict"/> based on the results of the initialization.</returns>
        /// <exception cref="ArgumentNullException">The test case isn't loaded corrrectly (is null).</exception>
        public TestCaseVerdict InitTestCase(TestCase testCase)
        {
            if (testCase == null) throw new ArgumentNullException(nameof(testCase), "Test case cannot be null.");
            testCase.Verdict = _userSourceLinkerService.RunCppExecutable(testCase);

            if (testCase.Verdict == TestCaseVerdict.Passed)
                testCase.Verdict = RunTest(testCase.ExpectedOutput);

            return testCase.Verdict;
        }
        
        /// <summary>
        /// Compares the expected output with the output generated by the user's executable.
        /// </summary>
        /// <param name="_expectedOutput">The correct output for the given test case.</param>
        /// <returns>A <see cref="TestCaseVerdict"/> based on the results of the tests.</returns>
        private TestCaseVerdict RunTest(string _expectedOutput)
        {
            TestCaseVerdict verdict = TestCaseVerdict.Passed;

            string[] userOutput = _userOutputService.UserOutput.Split(new[] { ' ', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
            string[] expectedOutput = _expectedOutput.Split(new[] { ' ', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);

            if (userOutput.Length < expectedOutput.Length)
            {
                verdict = TestCaseVerdict.TooFewArguments;
                return verdict;
            }

            if (userOutput.Length > expectedOutput.Length)
            {
                verdict = TestCaseVerdict.TooManyArguments;
                return verdict;
            }

            for (int i = 0; i < userOutput.Length; i++)
            {
                if (userOutput[i] != expectedOutput[i])
                {
                    verdict = TestCaseVerdict.IncorrectAnswer;
                    break;
                }
            }

            return verdict;
        }

        /// <summary>
        /// Saves a <see cref="TestCase"/> to the database.
        /// </summary>
        /// <param name="testCase">The test case that needs to be saved.</param>
        public async Task SaveToDatabase(TestCase testCase)
        {
            await _unitOfWork.BeginTransactionAsync();
            try
            {
                
                _unitOfWork.TestCaseRepository.SaveToDatabase(testCase);
                await _unitOfWork.CommitAsync();
                await _unitOfWork.CommitTransactionAsync();
            }
            catch { await _unitOfWork.RollbackTransactionAsync(); }
        }
    }
}

