using CustomDSATrainer.Domain.Interfaces.Services;

namespace CustomDSATrainer.Application.Services
{
    /// <summary>
    /// Provides the functionality to get and set the output generated by the user's executable when running it through test cases.
    /// </summary>
    public class UserOutputService : IUserOutputService
    {
        private string _userOutput = string.Empty;

        public string? UserOutput
        {
            get => _userOutput;
            set => _userOutput = value;
        }

    }
}
